# Generated by Django 5.2.7 on 2025-10-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('ARICA', 'XV - Arica y Parinacota'), ('TARAPACA', 'I - Tarapacá'), ('ANTOFAGASTA', 'II - Antofagagasta'), ('ATACAMA', 'III - Atacama'), ('COQUIMBO', 'IV - Coquimbo'), ('VALPARAISO', 'V - Valparaíso'), ('METROPOLITANA', 'RM - Metropolitana de Santiago'), ('OHIGGINS', "VI - O'Higgins"), ('MAULE', 'VII - Maule'), ('NUBLE', 'XVI - Ñuble'), ('BIOBIO', 'VIII - Biobío'), ('ARAUCANIA', 'IX - La Araucanía'), ('RIOS', 'XIV - Los Ríos'), ('LAGOS', 'X - Los Lagos'), ('AYSEN', 'XI - Aysén del G. Carlos Ibáñez del Campo'), ('MAGALLANES', 'XII - Magallanes y la Antártica Chilena')], max_length=50, verbose_name='Región')),
                ('año', models.IntegerField(verbose_name='Año del Registro')),
                ('temp_max_anual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura Máxima Anual (°C)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Clima',
                'verbose_name_plural': 'Registros de Clima',
                'unique_together': {('region', 'año')},
            },
        ),
    ]
